apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesync-webapp
  labels:
    app: filesync-webapp
spec:  # Move spec here
  replicas: 1  # This should be under spec
  selector:  # This should also be under spec
    matchLabels:
      app: filesync-webapp
  template:
    metadata:
      labels:
        app: filesync-webapp
    spec:
      containers:
      - name: filesync-webapp
        image: s4msepiol/filesync_docker:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/git-logs" # Use the MongoDB service name
---
apiVersion: v1
kind: Service
metadata:
  name: filesync-webapp
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003 # Optional, specify a port if needed
  selector:
    app: filesync-webapp
